[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Optional: just to be explicit about your env vars
  VITE_FIREBASE_API_KEY="dummy"
  VITE_FIREBASE_APP_ID="dummy"
  VITE_FIREBASE_AUTH_DOMAIN="dummy"
  VITE_FIREBASE_MEASUREMENT_ID="dummy"
  VITE_FIREBASE_MESSAGING_SENDER_ID="dummy"
  VITE_FIREBASE_PROJECT_ID="dummy"
  VITE_FIREBASE_STORAGE_BUCKET="dummy"

[secrets]
  # Tell Netlify to ignore these keys
  omit_keys = [
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_APP_ID",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_MEASUREMENT_ID",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_STORAGE_BUCKET"
  ]

  # Ignore Firebase config files too
  omit_paths = [".firebaserc"]
